# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100, verbose_name='Host')),
                ('ip', models.CharField(max_length=255, verbose_name='IP')),
                ('port', models.CharField(max_length=6, verbose_name='Porta')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ip'],
                'verbose_name': 'Host',
                'verbose_name_plural': 'Hosts',
            },
        ),
    ]
